version: '3'
services:
  twitthon:
    image: reachhubcorp/twitthon:latest
    container_name: twitthon
    build:
      context: ./context/
    environment:
          KAFKA_IP: "${ipkafka}"
          KAFKA_PORT: 8092
          TOPIC_IN: housToTwit
          TOPICTWEET_OUT: tweetToColissi
          TOPICTMEDIA_OUT: tweetToCrousti
          TOPICTWEET_OUTDEUX: textToNER
          OUTPUTTWEET_USER: /app/timeline/json
          OUTPUTMEDIA_USER: /app/timeline/media
          OUTPUTTWEET_KEYWORDS: /app/keywords/json
          OUTPUTMEDIA_KEYWORDS: /app/keywords/media
          LIMIT: 10
          DEBUG_LEVEL: INFO
